#!/bin/bash
# maintenance-report.sh — Consolidated weekly maintenance digest
# Schedule: Sunday 3:15 AM

source /opt/homelab/configs/.env

LOG_DIR="/var/log/maintenance"
HOSTNAME_LABEL=$(hostname)
TODAY=$(date '+%Y-%m-%d')
RUN_TIME=$(date '+%A, %B %d, %Y at %H:%M')

get_log() { grep "^\[$TODAY" "$LOG_DIR/$1" 2>/dev/null; }
last_line() { get_log "$1" | grep -i "$2" | tail -1; }

{
    echo "Subject: [${HOSTNAME_LABEL}] Sunday Maintenance Report - ${TODAY}"
    echo ""
    echo "Proxmox Maintenance - Weekly Digest"
    echo "$RUN_TIME"
    echo "========================================"
    echo ""

    # --- Proxmox Host ---
    echo "PROXMOX HOST"
    echo "------------"
    PROX=$(get_log "proxmox-update.log")
    if echo "$PROX" | grep -q "No packages"; then
        echo "  ✓ Up to date"
    elif echo "$PROX" | grep -q "Packages updated"; then
        echo "  ↑ $(echo "$PROX" | grep "Packages updated" | tail -1 | sed 's/.*Packages updated: //')"
    else
        echo "  ✗ No status found"
    fi
    echo ""

    # --- LXC Updates ---
    echo "LXC CONTAINERS"
    echo "--------------"
    LXC=$(get_log "lxc-update.log")
    if [ -z "$LXC" ]; then
        echo "  No status found"
    else
        echo "$LXC" | grep "CT [0-9]" | while IFS= read -r line; do
            echo "  $line" | sed 's/.*\] //'
        done
    fi
    echo ""

    # --- *arr Apps ---
    echo "ARR APPLICATIONS"
    echo "----------------"
    ARR=$(get_log "arr-update.log")
    if [ -z "$ARR" ]; then
        echo "  No status found"
    else
        echo "$ARR" | grep -E "triggered|FAILED" | while IFS= read -r line; do
            echo "  $line" | sed 's/.*\] //'
        done
    fi
    echo ""

    # --- Seerr ---
    echo "SEERR"
    echo "-----"
    SEERR=$(last_line "seerr-update.log" "updated\|FAILED")
    [ -z "$SEERR" ] && echo "  No status found" || echo "  $SEERR" | sed 's/.*\] //'
    echo ""

    # --- Bazarr ---
    echo "BAZARR"
    echo "------"
    BAZARR=$(last_line "bazarr-update.log" "triggered\|FAILED")
    [ -z "$BAZARR" ] && echo "  No status found" || echo "  $BAZARR" | sed 's/.*\] //'
    echo ""

    # --- rdt-client ---
    echo "RDT-CLIENT"
    echo "----------"
    RDTC=$(last_line "rdtclient-update.log" "up to date\|updated to\|FAILED")
    [ -z "$RDTC" ] && echo "  No status found" || echo "  $RDTC" | sed 's/.*\] //'
    echo ""

    # --- Unpackerr ---
    echo "UNPACKERR"
    echo "---------"
    UNPACK=$(last_line "unpackerr-update.log" "complete\|FAILED")
    [ -z "$UNPACK" ] && echo "  No status found" || echo "  $UNPACK" | sed 's/.*\] //'
    echo ""

    # --- Pi-hole ---
    echo "PI-HOLE"
    echo "-------"
    PIHOLE=$(get_log "pihole-update.log")
    if [ -z "$PIHOLE" ]; then
        echo "  No status found"
    else
        echo "$PIHOLE" | grep -E "OK|FAILED" | while IFS= read -r line; do
            echo "  $line" | sed 's/.*\] //'
        done
    fi
    echo ""

        # --- Homarr ---
    echo "HOMARR"
    echo "------"
    HOMARR=$(last_line "homarr-update.log" "Update OK\|FAILED")
    [ -z "$HOMARR" ] && echo "  No status found" || echo "  $HOMARR" | sed 's/.*\] //'
    echo ""

    # --- All Errors ---
    echo "ERRORS & WARNINGS"
    echo "-----------------"
    ALL_ERRORS=$(grep "^\[$TODAY" "$LOG_DIR"/*.log 2>/dev/null | grep -i "ERROR\|FAILED" | grep -v premiumize)
    if [ -z "$ALL_ERRORS" ]; then
        echo "  None"
    else
        echo "$ALL_ERRORS" | sed 's/.*\] /  /' | head -20
    fi
    echo ""
    echo "========================================"
    echo "Logs: $LOG_DIR"
    echo "Generated by maintenance-report on ${HOSTNAME_LABEL}"

} | msmtp "$EMAIL"

exit 0